frappe.query_reports["US Lead Generation Report"] = {
    filters: [
        {
            fieldname: "from_date",
            label: __("From Date"),
            fieldtype: "Date",
            default: frappe.datetime.add_months(frappe.datetime.get_today(), -1),
            reqd: 1,
        },
        {
            fieldname: "to_date",
            label: __("To Date"),
            fieldtype: "Date",
            default: frappe.datetime.get_today(),
            reqd: 1,
        },
        {
            fieldname: "emp_team",
            label: __("EMP Team"),
            fieldtype: "Select",
            options: "\nChennai\nDubai\nMadurai",
        },
        {
            fieldname: "emp_code",
            label: __("EMP Code"),
            fieldtype: "Link",
            options: "Employee",
        },
        {
            fieldname: "assigned_by",
            label: __("Assigned To"),
            fieldtype: "Link",
            options: "Employee",
        },
        {
            fieldname: "team",
            label: __("Team"),
            fieldtype: "Select",
            options: "\nChennai\nDubai\nMadurai",
        },
        {
            fieldname: "lead_source",
            label: __("Lead Source"),
            fieldtype: "Link",
            options: "Lead Source",
        },
        {
            fieldname: "eligibility",
            label: __("Eligibility"),
            fieldtype: "Select",
            options: "\nEligible\nNot Eligible\nAlready Subscribed\nRepeated",
        },
        {
            fieldname: "us_status",
            label: __("Status"),
            fieldtype: "Select",
            options: "\nDropped\nIn Process\nNot Eligible\nSubscribed\nReminder Month",
        },
        {
            fieldname: "progress",
            label: __("Progress"),
            fieldtype: "Select",
            options: "\nAlready Subscribed / Repeated\nDemate Only\nDropped\nExpensive\nGen. Enquiry / Prospect / Will get back\nIBKR link sent / Funding in process\nNo Response\nNot Eligible\nNot interested\nPayment link sent / Risk form sent\nReminder Month\nSubscribed",
        },
        {
            fieldname: "employment_status",
            label: __("Employment Status"),
            fieldtype: "Select",
            options: "\nEmployed\nSelf Employed\nStudent\nHomemaker\nRetired",
        },
        {
            fieldname: "country_of_residence",
            label: __("Country of Residence"),
            fieldtype: "Link",
            options: "Country",
        },
        {
            fieldname: "month",
            label: __("Month"),
            fieldtype: "Select",
            options: "\nJanuary 2024\nFebruary 2024\nMarch 2024\nApril 2024\nMay 2024\nJune 2024\nJuly 2024\nAugust 2024\nSeptember 2024\nOctober 2024\nNovember 2024\nDecember 2024\nJanuary 2025\nFebruary 2025\nMarch 2025\nApril 2025\nMay 2025\nJune 2025\nJuly 2025\nAugust 2025\nSeptember 2025\nOctober 2025\nNovember 2025\nDecember 2025\nJanuary 2026\nFebruary 2026\nMarch 2026\nApril 2026\nMay 2026\nJune 2026\nJuly 2026\nAugust 2026\nSeptember 2026\nOctober 2026\nNovember 2026\nDecember 2026",
        },
        {
            fieldname: "year",
            label: __("Year"),
            fieldtype: "Select",
            options: "\n2024\n2025\n2026\n2027\n2028",
        },
    ],
};